### ISSUE TITLE
WEBP images not visible on ipad/iphone ios

### ISSUE THREAD

**Issue by valentinvieriu** [k-l-lambda/k-l-lambda.github.io#4]
Just a side note, you cannot see the images on your blog. IOS does not yet support WEBP

**Comment by k-l-lambda** [comment]
Thanks for your report. It seems I triggered a common iOS trouble. I'll handle this.

**Comment by valentinvieriu** [comment]
Yep, I know, it'a bummer. Would be great to be able to use wbp on ios, but I don't think will happen soon. Classical jpeg is the only way for cross platform compatibility.
